### PR TITLE
Update Accept header to allow JSON response

### PR DESCRIPTION
**Pull request by libcthorne**
This is to match https://github.com/ArweaveTeam/arweave-js/blob/099ca77ae6d6cd854d9d24fa1b4efe2b4b36e4aa/src/common/lib/api.ts#L69

Docs: https://docs.arweave.org/developers/server/http-api#submit-a-transaction

image

### CODE REVIEW

**Comment by libcthorne** [comment]
@MikeHibbert Thanks for the quick merge! Would it be possible to also publish a new PyPI release? (https://pypi.org/project/arweave-python-client/)

**Comment by MikeHibbert** [comment]
I'll try and schedule some time over the weekend I'm afraid as I'm working for clients today.

**Comment by MikeHibbert** [comment]
@libcthorne Thats now built and published

**Comment by libcthorne** [comment]
@MikeHibbert Thank you!

**Pull request merged**
