### PR TITLE
Fixed wrong conversion methods

### PR DESCRIPTION
**Pull request by fabianriewe**

### CODE REVIEW

**Comment by fabianriewe** [comment]
I think I made a mistake. The function needs to return a str

**Comment by MikeHibbert** [comment]
What reasons do you think its wrong in the previous method of conversion?

**Comment by fabianriewe** [comment]
These are the results when using the 'original' functions.
```python
###
# Some real tx data
# "fee": {
# "winston": "938884",
# "ar": "0.000000938884"
# }
##

winston_str = "938884"
print(winston_to_ar(winston_str))  # -> returns 0.938884, should return 0.000000938884
# (they are followed by 0, but the 0 need to be leading)
# I noticed, that I just needed to swap format
ar_amount = "0.000000938884"
print(ar_to_winston(ar_amount))  # -> returns error: ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by fabianriewe** [comment]
Any updates on this?

**Comment by MikeHibbert** [comment]
Sorry for the late response but thanks for this correction :+1:

**Pull request merged**
