### PR TITLE
Separate network calls out into a Peer class

### PR DESCRIPTION
**Pull request by xloem**
Consapsulates network functionality into a single reusable class available to users.﻿

### CODE REVIEW

**Comment by MikeHibbert** [comment]
What problem does this solve?

**Comment by xloem** [comment]
Writing client apps that connect to multiple peers on the arweave network.

**Comment by xloem** [comment]
If you'd rather not make changes like this, do you have any information on new coding norms where factoring is no longer considered valuable?

**Comment by xloem** [comment]
@MikeHibbert I'm sorry, I have so poor interpersonal skills.

I'm interested in writing a peer to peer app on arweave in python. Is this the right library for the job? Would you be interested in contributions focused around peer to peer usage?

**Comment by MikeHibbert** [comment]
> @MikeHibbert I'm sorry, I have so poor interpersonal skills.
> 
> I'm interested in writing a peer to peer app on arweave in python. Is this the right library for the job? Would you be interested in contributions focused around peer to peer usage?

Its open source so your welcome to fork and add in project specific code for your own library?

I do see that it would be nice to have p2p but perhaps keep that in your custom version?

**Comment by xloem** [comment]
You dislike the change?

**Comment by MikeHibbert** [comment]
> You dislike the change?

No I think its a good idea for a new support lib but not as a main feature in this base lib

**Comment by xloem** [comment]
To clarify, it's an underlying change, not a higher-level interface change. I unified the peer functions into a single class, which both existing classes now use.

Do you see how it makes sense in a base lib?

**Comment by xloem** [comment]
I am inferring that both of us kind of struggle to do this with much effectiveness.

Maybe I will make a tiny pip library of my own :)

**Pull request closed without merging**
